### ISSUE TITLE
dynamicity

### ISSUE THREAD

**Issue by rihorn** [rihorn/kybiodiversity#1]
I want to add the legend to the map and have it dynamically enabled so that it changes with each `taxonomy-selector` value.  Also, I need the `tooltip` to change from each selected value.  Currently, it's programmed to just use `Animals` values.  I feel like I'm so close on this.  Clues or hints on documentation are welcome.

Thanks,

Ian

**Comment by rgdonohue** [comment]
The script was throwing an error on line 180, "breaks is not defined."

![image](https://user-images.githubusercontent.com/1952205/37480415-d0ce7cf6-2844-11e8-96ae-411d3ca68b60.png)

Because `breaks` isn't available within that drawMap() function at line 180, nor do you need breaks there. You're just adding the empty legend.

Try removing `breaks` and just calling the function: `addLegend();`

**Comment by rgdonohue** [comment]
Also, I will be chastised and possibly assassinated by the cartographic community for letting a color scheme like this loose in the wild:

![image](https://user-images.githubusercontent.com/1952205/37480549-20190a38-2845-11e8-9a6b-fba6606121fe.png)

A nominal color scheme like this is useful for nominal data (un-orderable categories). Yellow isn't less than red, purple isn't more than yellow. Looking at the map there's no intrinsic sense of which squares contain more of your phenomena. 

A sequential color scheme, however, allows the user to see, without even looking at the legend, which features have more/less, higher/lower amounts ...

![image](https://user-images.githubusercontent.com/1952205/37480796-c2afcd0e-2845-11e8-8e14-f220704baed3.png)
